export const carouselData = [
    {
        "Id":"9f84e8d8-b4b3-401f-9318-00f4654a2c13",
        "CreatedDateTime":1625254615,
        "ModifiedDateTime":1625260257,
        "order":2,
        "link":"http://bepensaconect.com:9000/Cummins/",
        "name":"banners 2",
        "active":"Si",
        "section":"Detalle de Pedido",
        "regions":"Noroeste,Occidente",
        "slogan":"banners texto 2",
        "image_banner":"https://proindusquim.com/wp-content/uploads/2016/03/BANNER-WEB-LINEA-AUTOMOTRIZ-2.png",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"7375bc5b-3628-439e-a5b0-3d95aa24b1af",
        "CreatedDateTime":1625151100,
        "ModifiedDateTime":1625258738,
        "order":1,
        "link":"https://dashboard.sandbox.arcadier.io/package",
        "name":"BANNER 1",
        "active":"Si",
        "regions":"Noroeste",
        "section":"Home",
        "slogan":"TEXTO BANNER 1 HOME ",
        "image_banner":"https://static1.concesiones.quadis.es/wp-content/uploads/sites/66/2020/08/Banner-Gama-de-vehi%CC%81culos-AR-Motors.jpg",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"f5865a1f-dfe1-439d-9663-3e21347437f3",
        "CreatedDateTime":1625259690,
        "ModifiedDateTime":1625271706,
        "order":1,
        "link":"http://bepensaconect.com:9000/Cummins/\t",
        "name":"COE2",
        "active":"No",
        "slogan":"116+",
        "section":"Detalle de Pedido",
        "regions":"Noroeste,Occidente,Oriente,Pacífico,Sureste",
        "image_banner":"https://proindusquim.com/wp-content/uploads/2016/03/BANNER-WEB-LINEA-AUTOMOTRIZ-2.png",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"71b675cd-2706-47f0-bcb8-a1a84a06c2ab",
        "CreatedDateTime":1625348001,
        "ModifiedDateTime":1625348001,
        "order":3,
        "link":"https://www.google.com.mx/",
        "name":"Banner Prueba",
        "active":"Si",
        "section":"Home",
        "slogan":"Prueba Smz",
        "regions":"Occidente",
        "image_banner":"https://proindusquim.com/wp-content/uploads/2016/03/BANNER-WEB-LINEA-AUTOMOTRIZ-2.png",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"3d9619fc-5118-4c88-bbbc-ab915ab27eda",
        "CreatedDateTime":1625271680,
        "ModifiedDateTime":1625271680,
        "order":4,
        "name":"PERSONA","link":"https://www.google.com.mx/",
        "section":"Home",
        "slogan":"Text ",
        "active":"Si",
        "image_banner":"\thttps://proindusquim.com/wp-content/uploads/2016/03/BANNER-WEB-LINEA-AUTOMOTRIZ-2.png",
        "regions":"Noroeste,Occidente",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"9c619ee2-8c08-4661-9f16-b7fa3d91d133",
        "CreatedDateTime":1625348001,
        "ModifiedDateTime":1625348041,
        "order":3,
        "name":"Banner Prueba","link":"https://www.google.com.mx/",
        "slogan":"Prueba Smz",
        "active":"No",
        "section":"Home",
        "regions":"Occidente",
        "image_banner":"https://proindusquim.com/wp-content/uploads/2016/03/BANNER-WEB-LINEA-AUTOMOTRIZ-2.png",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"210a9b70-93e5-40cd-8bee-c5ee49f985ae",
        "CreatedDateTime":1625348001,
        "ModifiedDateTime":1625348001,
        "order":3,
        "name":"Banner Prueba","link":"https://www.google.com.mx/",
        "active":"Si",
        "section":"Home",
        "slogan":"Prueba Smz",
        "regions":"Occidente",
        "image_banner":"https://proindusquim.com/wp-content/uploads/2016/03/BANNER-WEB-LINEA-AUTOMOTRIZ-2.png",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"524b4532-820c-481b-ba7c-e94cddcd0910",
        "CreatedDateTime":1625254847,
        "ModifiedDateTime":1625267115,
        "order":3,
        "name":"detalle pedido 25","link":"https://kenwheeler.github.io/slick/",
        "section":"Detalle de Pedido ",
        "active":"No",
        "slogan":"text 233333",
        "image_banner":"http://www.legaltec.cl/images/mercados/img_automotriz.jpg",
        "regions":"Noroeste,Occidente",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"6af47846-9f74-4ef6-a82b-ebc59449a15b",
        "CreatedDateTime":1625261367,
        "ModifiedDateTime":1625261367,
        "order":2,
        "name":"banner 2","link":"https://www.google.com.mx/",
        "slogan":"texto banner 2",
        "section":"Home",
        "active":"Si",
        "regions":"Noroeste,Occidente",
        "image_banner":"\thttps://static1.concesiones.quadis.es/wp-content/uploads/sites/66/2020/08/Banner-Gama-de-vehi%CC%81culos-AR-Motors.jpg",
        "banner_id":null,
        "click_counter":null
    },
    {
        "Id":"3778dd6a-7178-4ded-a478-eecf2f20a8e0",
        "CreatedDateTime":1625255098,
        "ModifiedDateTime":1625259830,
        "order":4,
        "link":"http://bepensaconect.com:9000/Cummins/","name":"banner 4",
        "slogan":"text banner 4",
        "section":"Detalle de Pedido",
        "active":"No",
        "image_banner":"https://proindusquim.com/wp-content/uploads/2016/03/BANNER-WEB-LINEA-AUTOMOTRIZ-2.png",
        "regions":"Noroeste,Occidente",
        "banner_id":null,
        "click_counter":null
    }
];